AWSTemplateFormatVersion: '2010-09-09'
Description: 'Noporverse Graph API DataSources'

Parameters:
  Project:
    Type: String
    Description: 'The name of the project.'
  Stage:
    Type: String
    Default: dev
    Description: 'The stage of the application.'

Resources:
  ServiceMeetingsDS:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId:
        Fn::ImportValue: !Sub "${Project}-api-id-${Stage}"
      Name: !Sub "ServiceMeetingsDS_${Stage}"
      Type: AWS_LAMBDA
      LambdaConfig:
        LambdaFunctionArn:
          Fn::ImportValue: !Sub "${Project}-service-meetings-${Stage}"
      ServiceRoleArn:
        Fn::ImportValue: !Sub "${Project}-APILambdaInvokeAllRole-${Stage}"