AWSTemplateFormatVersion: '2010-09-09'
Description: 'Project Graph API Resolvers'

Parameters:
  Project:
    Type: String
    Description: 'The name of the project.'
  Stage:
    Type: String
    Default: dev
    Description: 'The stage of the application.'

Resources:
  RetrieveSubjectCategoriesResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::ImportValue: !Sub "${Project}-api-id-${Stage}"
      TypeName: Query # Or Query
      FieldName: retrieveSubjectCategories
      DataSourceName: !Sub "ServiceCatalogsDS_${Stage}"
  RetrieveStudentsResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::ImportValue: !Sub "${Project}-api-id-${Stage}"
      TypeName: Query # Or Query
      FieldName: retrieveStudents
      DataSourceName: !Sub "ServiceStudentsDS_${Stage}"
  RetrieveSubjectCollaboratorsResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::ImportValue: !Sub "${Project}-api-id-${Stage}"
      TypeName: Query # Or Query
      FieldName: retrieveSubjectCollaborators
      DataSourceName: !Sub "ServiceSubjectsDS_${Stage}"
  RetrieveSubjectsResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::ImportValue: !Sub "${Project}-api-id-${Stage}"
      TypeName: Query # Or Query
      FieldName: retrieveSubjects
      DataSourceName: !Sub "ServiceSubjectsDS_${Stage}"